version: '3'
services:
  db:
    image: postgres
    volumes:
      - ../../tmp/db:/var/lib/postgresql/data
  web_app:
    build: ../../
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../../:/my_app
    environment:
      RAILS_ENV: "development"
    ports:
      - "3000:3000"
    depends_on:
      - db
